### ISSUE TITLE
CWD is never updated

### ISSUE THREAD

**Issue by glandium** [magiclen/path-dedot#2]
I was using path-absolutize, and got wrong results in some case, which turned out to be because it's using path-dedot's CWD, that is never updated, so when a program changes its current directory during execution, path-absolutize returns wrong results.

The following test shows the problem:
```
use std::path::Path;
use path_absolutize::Absolutize;

#[test]
fn test() {
    assert_eq!(Path::new(".").absolutize().unwrap(), Path::new(".").canonicalize().unwrap());
    std::env::set_current_dir("/");
    assert_eq!(Path::new(".").absolutize().unwrap(), Path::new(".").canonicalize().unwrap());
}
```

The first `assert_eq` passes, not the second one (except if you start the program from /).

**Comment by magiclen** [comment]
I never thought the case that an application change its current directory during execution. I made some changes to this crate. There is a function named `update_cwd` can be called after `set_current_dir`.

Example:

```rust
use std::path::Path;
use path_absolutize::{Absolutize, update_cwd};

#[test]
fn test() {
    assert_eq!(Path::new(".").absolutize().unwrap(), Path::new(".").canonicalize().unwrap());
    std::env::set_current_dir("/");
    unsafe { update_cwd(); }
    assert_eq!(Path::new(".").absolutize().unwrap(), Path::new(".").canonicalize().unwrap());
}
```

I didn't want to `get_current_dir` every time when running `absolutize` and `parse_dot` methods because that will create many `PathBuf` objects to represent the same CWD.

**Comment by glandium** [comment]
That doesn't help when the change of current directory happens from FFI code :(

**Comment by magiclen** [comment]
Maybe you can call `update_cwd()` every time before you use the `absolutize` method.

**Comment by magiclen** [comment]
I reopened this issue because the solution was too unsafe and a bit annoying.

**Comment by magiclen** [comment]
After v2.0.0, this crate does not cache the CWD by default. The caching mechanism can be activated by enabling the `lazy_static_cache` feature or the `unsafe_cache` feature.
