### ISSUE TITLE
Dot doesn't get reduced

### ISSUE THREAD

**Issue by gergelyk** [magiclen/path-dedot#5]
Dot doesn't get reduced in the second example. Is this expected?

```rust
// this:
let p = Path::new("/path/to/../123/456/./777");
println!("{}", p.parse_dot().unwrap().to_str().unwrap());
// gives: /path/123/456/777

// but this:
let p = Path::new("/path/to/123/456/./777");
println!("{}", p.parse_dot().unwrap().to_str().unwrap());
// gives: /path/to/123/456/./777
```

**Comment by magiclen** [comment]
I'm still finding a good way to solve this. The tricky part is that the `Components` iterator ignores the single dot if it is not the first component. We can simply assume `has_dots` is **true** to solve this, but that will generate unnecessary `PathBuf` instances.

**Comment by magiclen** [comment]
It's been fixed by using another way to pre-calculate the output size which is accurate. If `has_dots` is **false**, check whether the pre-calculated size is equal to the size of the original path.

aaf37016c1bb12fe4cf88378ce3f2d1fe71700c8
